### ISSUE TITLE
Rename function to better reflect functionality. Also, a bug.

### ISSUE THREAD

**Issue by millercommamatt** [torimcd/impacts_tools#2]
https://github.com/torimcd/impacts_tools/blob/a5b5902261cf1425906a793880b125e6360f4f0d/src/impacts_tools/er2.py#L101

This function removes data where the roll is greater than some user-input value. Nothing is corrected. Maybe call the function `mask_roll`?

Also, roll angle is signed and I don't see where an absolute value is taken. So a large negative roll angle will not be removed.

**Comment by torimcd** [comment]
Thanks! Fixed.
